# Generated by Django 4.2.7 on 2023-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_posted', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(null=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
